install:
  - sudo apt-get install pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended

script:
  - pandoc example.md -o my_pdf.pdf
  # Check if the PDF has been created
  - if [ ! -e my_pdf.pdf ]; then exit 1; fi